# 1. Copy this file to /etc/nginx/snippets
# 2. Include it inside your server {} config: include snippets/security-traps.conf;
# 3. Check and restart your nginx server: nginx -t && nginx -s reload

# Scanner trap endpoints
location ~* (\.env|\.git|\.aws|\.DS_Store|phpinfo\.php|composer\.json|vendor/phpunit|wp-admin/install\.php) {
    access_log /var/log/nginx/honeypot.log;
    return 403;
}

# Tarpit scanners
location ~* (\.sql|\.bak|\.backup|\.old|\.tar|\.zip) {
    limit_rate 1k;
    return 403;
}
